### ISSUE TITLE
After release 1.5.1, cstore_fdw now can't use parallel COPY processes

### ISSUE THREAD

**Issue by luiscape** [citusdata/cstore_fdw#142]
We have noticed a notable change from `v1.5.0` to `v1.5.1`: locks on parent tables when using `INHERIT`.  This affects the creation of partitioned tables in parallel. After `v1.5.1` parallel processes that inherit from the same table don't work anymore. Each `COPY` process makes the other wait until the lock is released. These locks weren't happening before.

As follows, I present the steps to reproduce -- run the following in two PostgreSQL instances, one with `v1.5.0` and one with `v1.5.1`. I will be using [GNU parallel](https://www.gnu.org/software/parallel/) for managing the parallelization process.

### Step 1: Create parent tables
```sql
CREATE SCHEMA IF NOT EXISTS events;
    
    CREATE TABLE IF NOT EXISTS events.calls(

        id TEXT,

        outgoing BOOLEAN,

        datetime TIMESTAMPTZ NOT NULL,
        duration NUMERIC,

        network TEXT,

        msisdn TEXT NOT NULL,
        msisdn_counterpart TEXT,

        location_id TEXT,

        imsi TEXT,
        imei TEXT,
        tac NUMERIC(8),

        operator_code NUMERIC,
        country_code NUMERIC

        );
```

### Step 2: Create the parametrized ingestion script `ingest.sh`
```sql
#!/bin/bash

STOP=$(date -d "$1 +1days" "+%Y%m%d")
TEST_DATA_PATH=$2

echo "Creating calls tables events.calls_$1"
psql -U user -d database -c "
BEGIN;

    CREATE FOREIGN TABLE IF NOT EXISTS events.calls_$1 (
        CHECK ( 
                    datetime >= '$1'::TIMESTAMPTZ AND 
                    datetime < '$STOP'::TIMESTAMPTZ
            )
    )
    INHERITS (events.calls)
    SERVER cstore_server
    OPTIONS (compression 'pglz');

CREATE FOREIGN TABLE IF NOT EXISTS temp_$1 (
    start_time TIMESTAMPTZ,
    msisdn_counterpart TEXT,
    id TEXT,
    msisdn TEXT,
    location_id TEXT,
    outgoing BOOL,
    duration NUMERIC
) SERVER csv_fdw
OPTIONS (filename '$TEST_DATA_PATH', 
         format 'csv', header 'true');

INSERT INTO events.calls_$1 (id, msisdn, 
                             msisdn_counterpart, outgoing,
                             datetime, duration, location_id) (
    SELECT
        id,
        msisdn,
        msisdn_counterpart,
        outgoing,
        start_time AS datetime,
        duration,
        location_id
    FROM temp_$1
    );

END;
"
```

### Step 3: Ingest data using `parallel` by fetching the parameters from the file `tries.txt`
```
$ parallel bash ingest.sh {} example_data.csv ::: $(cat tries.txt)
```

**Warning**: Due to a data-loss bug that was fixed in `v1.5.1` all data will be lost when running step 3 for the first time. Maybe the fix implemented in `v1.5.1` caused these locks to happen.

When running the above on `v1.5.0` you will notice that the processes will use all available cores --
 this is great because now you can ingest quite lot of rows at the same time. When running on `v1.5.1`, the first `COPY` routine will block the following, and so on for all that follow, limiting the `COPY` process to a single core.

You can find the files used in this example as follows:

* [`tries.txt`](https://drive.google.com/file/d/0BzNYvYpDh-daUXV3NDJsc1BuYXM/view?usp=sharing)
* [`example_data.csv.gz`](https://drive.google.com/file/d/0BzNYvYpDh-daa2x6a18yZFFEUUE/view?usp=sharing)

**Comment by mtuncer** [comment]
thanks @luiscape for the report I will look into this in next few days.

**Comment by luiscape** [comment]
@mtuncer thanks a lot! This is a fantastic product. We're looking forward to assisting a bit more in dealing with this issue.

**Comment by mtuncer** [comment]
Some update on this.
It looks like this is related to transactional behavior of creating inherited table. `create foreign table` command acquires a lock on the parent table `calls`. This lock effectively blocks the second transaction from creating an inherited table.

Issue could be replicated as follows

Transaction 1:
```sql
BEGIN;
    CREATE FOREIGN TABLE IF NOT EXISTS calls_20170203 (
        CHECK ( 
                    datetime >= '20170203'::TIMESTAMPTZ AND 
                    datetime < '20170204'::TIMESTAMPTZ
            )
    )
    INHERITS (calls)
    SERVER cstore_server
    OPTIONS (compression 'pglz');
```

Notice transaction 1 has not committed yet.

transaction 2 : executes similar code
```sql
BEGIN;
    CREATE FOREIGN TABLE IF NOT EXISTS calls_20170204 (
        CHECK ( 
                    datetime >= '20170204'::TIMESTAMPTZ AND 
                    datetime < '20170205'::TIMESTAMPTZ
            )
    )
    INHERITS (calls)
    SERVER cstore_server
    OPTIONS (compression 'pglz');
```

The second transaction is blocked since the first one acquired the lock on parent table and has not released yet.

Transaction 2 is unblocked as soon as transaction 1 commits and releases the lock.

One solution to issue you are having is to relax atomicity property and have the ingest script use 2 transactions, one to create child table and another to ingest data. This way you should be able to perform parallel insertions to different cstore tables.

**Comment by luiscape** [comment]
Hi @mtuncer got it. We'll give that a try. However, do you know why this behavior doesn't take place on `v1.5.0`?

**Comment by mtuncer** [comment]
I am getting the same behavior in v1.5.0.  
Only change introduced in v1.5.1 is not related to locking behavior. It only adds a check before already existing code block that briefly acquires an exclusive lock.

The same behavior could also be observed using a regular tables. The second transaction is blocked until the first one commits or aborts. See below.

### Transaction 1

```sql
BEGIN;
    CREATE TABLE IF NOT EXISTS calls_20170203 (
        CHECK ( 
                    datetime >= '20170203'::TIMESTAMPTZ AND 
                    datetime < '20170204'::TIMESTAMPTZ
            )
    ) INHERITS (calls);
```
Notice transaction 1 has not committed yet.


### Transaction 2 
```sql
BEGIN;
    CREATE TABLE IF NOT EXISTS calls_20170204 (
        CHECK ( 
                    datetime >= '20170204'::TIMESTAMPTZ AND 
                    datetime < '20170205'::TIMESTAMPTZ
            )
    ) INHERITS (calls);
```

So think this blocking behavior is related to Postgres inherited tables, rather than cstore_fdw.

You could try an alternate approach in ingest.sh.

1. create not-inherited foreign tables
2. ingest data
3. right before the commit make this cstore table child of `calls` table.

You will need to make 2 changes
Replace
```sql
CREATE FOREIGN TABLE IF NOT EXISTS events.calls_$1 (
        CHECK ( 
                    datetime >= '$1'::TIMESTAMPTZ AND 
                    datetime < '$STOP'::TIMESTAMPTZ
            )
    )
    INHERITS (events.calls)
    SERVER cstore_server
    OPTIONS (compression 'pglz');
```
with

```sql
CREATE FOREIGN TABLE IF NOT EXISTS events.calls_$1 (
        id TEXT,
        outgoing BOOLEAN,
        datetime TIMESTAMPTZ NOT NULL,
        duration NUMERIC,
        network TEXT,
        msisdn TEXT NOT NULL,
        msisdn_counterpart TEXT,
        location_id TEXT,
        imsi TEXT,
        imei TEXT,
        tac NUMERIC(8),
        operator_code NUMERIC,
        country_code NUMERIC,

        CHECK ( 
                    datetime >= '$1'::TIMESTAMPTZ AND 
                    datetime < '$STOP'::TIMESTAMPTZ
            )
    )
    SERVER cstore_server
    OPTIONS (compression 'pglz');
```


And right before the commit issue
```sql
 ALTER TABLE events.calls_$1 INHERIT events.calls;
```

`ALTER TABLE` command will still block each other, but since they are after data ingestion, and at the transaction commit time, it should not effect parallel insertion.

**Comment by luiscape** [comment]
@mtuncer this is great -- thank you for taking the time. We have implemented an approach similar to what you have suggested using `v1.5.1` and parallelization is working without issues. I'll be closing this issue as its core subject has now been addressed. 

Thanks again!
