### ISSUE TITLE
Is Postgres-XL supported yet?

### ISSUE THREAD

**Issue by LucasManto** [citusdata/cstore_fdw#151]

**Comment by mtuncer** [comment]
Unfortunately Postgres-XL support is not planned for the near future.

**Comment by ozgune** [comment]
Hi @LucasManto - We built cstore_fdw to work with Postgres and test changes against recent Postgres versions.

When users are looking to scale out their Postgres installations, we recommend using [Citus](https://github.com/citusdata/citus). Citus extends Postgres (rather than forking it) and works with all Postgres extensions, including cstore_fdw.

Could you elaborate a bit more on the use case you were planning to use cstore_fdw for?

**Comment by LucasManto** [comment]
I was really looking to scale out. Citus is just what I need.

Thank you @ozgune!
