### ISSUE TITLE
Clarification required: Are INSERTS supported or not?

### ISSUE THREAD

**Issue by dazzag24** [citusdata/cstore_fdw#169]
#90 and #91 suggest not.   

**However** there is a citusdata blog post here:

https://www.citusdata.com/blog/2015/10/05/combined-row-columnar-storage-postgres/

that relies on INSERTS working:
```
WITH migrate AS (DELETE FROM events_current WHERE event_date <= 20150131 RETURNING *)
INSERT INTO events_201501 SELECT * FROM migrate;
```
I have attempted something similar with my own tables and I get an "operation is not supported" error when I attempt the migration.  This is the same error that I get when I attempt to INSERT into my cstore_fdw foreign table.

```
WITH migrate AS (DELETE FROM catalogue RETURNING *) INSERT INTO archive_catalogue SELECT * FROM migrate;
ERROR:  operation is not supported
```
So now I am unclear if this is supposed to work or not??? Please help clarify.

**Comment by mtuncer** [comment]
Answer is unfortunately both yes and no.
cstore_fdw support bulk inserts in the form of 
```sql
insert into <cstore_table> select * from <some other query>
```

single row inserts in the form of
```sql
insert into <cstore_table> values (...)
```
are not supported even if values part contains values for multiple rows.

I have checked your queries, it should work as you provided. However if your ```catalogue``` table is also a cstore_fdw table, it won't because cstore_fdw does not support ```delete``` operation.

If you would like to move everything from one cstore_fdw table to another., you could perform this in 2 step process. 

```sql
insert into archive_catalogue select * from catalogue;
truncate catalogue;
```
