### ISSUE TITLE
Support for Heroku Postgres / Citus Data addon?

### ISSUE THREAD

**Issue by sgoley** [citusdata/cstore_fdw#235]
Hi - I'm aware that citus does have an addon for Citus Postgres already:
https://elements.heroku.com/addons/citus

And similarly there is a list of allowed pg extensions for Heroku's own Postgres implementation:
https://devcenter.heroku.com/articles/heroku-postgres-extensions-postgis-full-text-search

However - I was wondering if it was ever on the roadmap to have this extension supported by either service running on the Heroku hosting platform.

**Comment by thanodnl** [comment]
Hi @sgoley,

Thanks for reaching out and showing interest in using `cstore_fdw`.

As you have found Citus Cloud (our managed service) is integrated from within Heroku. Due to operational complexities when running High Available clusters in Citus Cloud we do not provide `cstore_fdw` as an extension on our managed service today. We have prototypes that integrate `cstore_fdw` with the Write Ahead Log of Postgres that would make it possible to provide High Availability for `cstore_fdw` tables. As stated before these are prototypes, so we do not feel confident using it at this moment to store customer data. If you are already using the Citus integration in Heroku you should be able to file a support ticket to get in touch with the team responsible for our managed service. They might have more details on when it is scheduled to provide `cstore_fdw` or have an alternative they can provide you with.

The second link is the documentation of Heroku Postgres. Citus Data is not affiliated with Heroku and has no influence over extensions they feel comfortable providing in _their_ managed service. If you feel `cstore_fdw` should be provided it's best to reach out to the Heroku team directly.

Given your question is around managed services and not the extension directly I will close the github issue. Please follow up with your managed service providers to express your desire to use our extension.
